""" User specific application settings """
import logging
PRINTER_MODEL = 'QL-500'
""" PRINTER_PRINTER = 'usb://0x04f9:0x2015' """
PRINTER_PRINTER = 'tcp://127.0.0.1:9100'

""" PRINTER_PRINTER = 'file:///dev/usb/lp1' """
""" file:///dev/lp/printers/usb-Brother_QL-500_F4Z731433 """

LABEL_DEFAULT_SIZE = '23x23'
LABEL_DEFAULT_SHAPE = 'SQUARE'
LABEL_DEFAULT_ORIENTATION = 'standard'
LABEL_DEFAULT_PRINT_COLOUR = 'Black'
LABEL_DEFAULT_FONT_FAMILY = 'Liberation Mono'
LABEL_DEFAULT_FONT_STYLE = 'Regular'
LABEL_DEFAULT_FONT_SIZE = 37
LABEL_DEFAULT_FONT_ALIGNMENT = 'Centre'
LABEL_DEFAULT_LINE_SPACING = 100
LABEL_DEFAULT_QR_SIZE = 6
#LABEL_DEFAULT_ERROR_CORRECTION = 'L'
LABEL_DEFAULT_MARGIN_TOP = 20
LABEL_DEFAULT_MARGIN_BOTTOM = 20
LABEL_DEFAULT_MARGIN_LEFT = 20
LABEL_DEFAULT_MARGIN_RIGHT = 20

#IMAGE_DEFAULT_MODE = ''
#IMAGE_DEFAULT_BW_THRESHOLD = ''